# site settings

title: 広木宏 / hiromu_dev
description: Programmer / Writer
taglong:
tagshort:
url: https://mgmyst.github.io
baseurl: /aboutme
permalink: pretty
repo: https://github.com/mgmyst/aboutme

# author settings

author:
  name: hiromu_dev
  email: mgmyst@me.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook:
  github: mgmyst
  instagram:
  linkedin:
  stackoverflow:
  twitter: hirogi_dev

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
